title: "[Q] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Not sure how something works? Ask here. The community and TextForge team will do their best to help.
  - type: textarea
    id: question
    attributes:
      label: Your question
      description: What would you like to know?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any background that helps us understand what you're trying to do.
